version: '3.7'
services:
  web:
    image: ${IMAGE_NAME}:${VERSION}
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./settings.js:/data/settings.js
      - ./images:/data/images
      - ./node_modules:/data/node_modules
      - ./input:/data/input

networks:
  default:
    external:
      name: rubikx-iot-nw
